/* script/bg_index.js —— **自動產生，不要手改**（`py tools/bg_index.py`）
 *
 * 背景「檔名 → 區域資料夾」的索引。資料上寫的 `bg` 是基底名（沒有資料夾），
 * 由 `modules/story.js` 的 `imgSrc()` 查這一張表補上區域（鐵律 7：組 URL 只有那一支）。
 *
 * ⚠⚠⚠ **查不到一律退回根目錄**（＝ ver -1376 搬檔之前的現況）：
 *   美術把新檔丟進 `resources/background/` 根目錄照樣跑得動，只是沒歸檔；
 *   忘了重跑工具的下場是「照舊」，不是「空背景」。
 * ⚠ 鑰匙是**小寫、去副檔名**的基底名（`bandNames` 會試大小寫變體，所以要忽略大小寫）。
 * ⚠ 交了新背景之後重跑一次：`py tools/bg_index.py`（同 `tools/bust.py` 的位置）。
 */
const G = {
  belisar: ['belisar_antechamber','belisar_armourgallery','belisar_bellroom','belisar_cages','belisar_candlewalk','belisar_capstan','belisar_catacomb','belisar_chandelierhall','belisar_chrismroom','belisar_cistern','belisar_crownroom','belisar_culvert','belisar_draincliff_dawn','belisar_draincliff_day','belisar_draincliff_dusk','belisar_draincliff_night','belisar_drywell','belisar_drywell_dawn','belisar_drywell_dusk','belisar_drywell_night','belisar_entryhall','belisar_entryhallactive','belisar_exterior_dawn','belisar_exterior_day','belisar_exterior_dusk','belisar_exterior_night','belisar_floodway','belisar_forge','belisar_foyer','belisar_foyer_dawn','belisar_foyer_dusk','belisar_foyer_night','belisar_greatcourt_dawn','belisar_greatcourt_day','belisar_greatcourt_dusk','belisar_greatcourt_flood_dawn','belisar_greatcourt_flood_day','belisar_greatcourt_flood_dusk','belisar_greatcourt_flood_night','belisar_greatcourt_night','belisar_greathall','belisar_guardtomb','belisar_lionspout','belisar_lionstair','belisar_mirrorwalk','belisar_muralgallery','belisar_oldaltar','belisar_oldaltaractive','belisar_orrery','belisar_ossuary','belisar_relicroom','belisar_rooffall_dawn','belisar_rooffall_day','belisar_rooffall_dusk','belisar_rooffall_night','belisar_sarcophagi','belisar_spiralwell','belisar_stairhall','belisar_stelewalk','belisar_stillpool','belisar_sunkencourt_dawn','belisar_sunkencourt_day','belisar_sunkencourt_dusk','belisar_sunkencourt_night','belisar_thronehall','belisar_triarch','belisar_waterjail'],
  canyon: ['_canyon_map','canyon_altar_day','canyon_altar_dusk','canyon_altar_night','canyon_bones_day','canyon_bones_dusk','canyon_bones_night','canyon_bridge_day','canyon_bridge_dusk','canyon_bridge_night','canyon_corridor_day','canyon_corridor_dusk','canyon_corridor_night','canyon_entry_day','canyon_entry_dusk','canyon_entry_night'],
  capital: ['capital_bistro_dawn','capital_bistro_day','capital_bistro_dusk','capital_bistro_night','capital_cafe','capital_church_dawn','capital_church_day','capital_church_dusk','capital_church_midnight','capital_church_night','capital_cityhall_dawn','capital_cityhall_day','capital_cityhall_dusk','capital_cityhall_midnight','capital_cityhall_night','capital_dock_dawn','capital_dock_day','capital_dock_dusk','capital_dock_night','capital_downtown_dawn','capital_downtown_day','capital_downtown_dusk','capital_downtown_midnight','capital_downtown_night','capital_firearm_dawn','capital_firearm_day','capital_firearm_dusk','capital_grocerie_dawn','capital_grocerie_day','capital_grocerie_dusk','capital_hotel_dawn','capital_hotel_day','capital_hotel_dusk','capital_hotel_night','capital_midtown_dawn','capital_midtown_day','capital_midtown_dusk','capital_midtown_midnight','capital_midtown_night','capital_restaurant','capital_square_dawn','capital_square_day','capital_square_dusk','capital_square_midnight','capital_square_night','capital_sweets','capital_uptown_dawn','capital_uptown_day','capital_uptown_dusk','capital_uptown_midnight','capital_uptown_night','captal_guild_dawn','captal_guild_day','captal_guild_dusk'],
  deck: ['deck_destroied','deck_rapidsail'],
  dunmor: ['dunmor_altar','dunmor_altarcourt','dunmor_bardsstep','dunmor_barrowfield','dunmor_boarstone','dunmor_boglane','dunmor_bogoffer','dunmor_brochbase','dunmor_brochtop','dunmor_cairn','dunmor_causeway','dunmor_chariotshed','dunmor_cistgrave','dunmor_crannog','dunmor_ditche','dunmor_ditchw','dunmor_dolmen','dunmor_druidhouse','dunmor_fogou','dunmor_gatecourt','dunmor_granary','dunmor_hallcourt','dunmor_headshrine','dunmor_henge','dunmor_innerditch','dunmor_innergate','dunmor_kilnyard','dunmor_kingsbarrow','dunmor_kingshall','dunmor_lakeshore','dunmor_lawstone','dunmor_mainstreet','dunmor_marketcross','dunmor_nemeton','dunmor_oakgrove','dunmor_oghamrow','dunmor_ossuary','dunmor_potters','dunmor_ramparte','dunmor_rampartw','dunmor_roundring','dunmor_sacredway','dunmor_skullniche','dunmor_smithy','dunmor_souterrain','dunmor_southgate','dunmor_springpool','dunmor_stonerow','dunmor_tannery','dunmor_treasury','dunmor_triskele','dunmor_watche','dunmor_watchw','dunmor_weaverhut','dunmor_wellsq'],
  eastport: ['east_bistro_dawn','east_bistro_day','east_bistro_dusk','east_bistro_night','east_cafe_dawn','east_cafe_day','east_cafe_dusk','east_cafe_night','east_church_dawn','east_church_day','east_church_dusk','east_church_night','east_customs_dawn','east_customs_day','east_customs_dusk','east_customs_night','east_dessert_dawn','east_dessert_day','east_dessert_dusk','east_dessert_night','east_dining_dawn','east_dining_day','east_dining_dusk','east_dining_night','east_dock_dawn','east_dock_day','east_dock_dusk','east_dock_night','east_firearm_dawn','east_firearm_day','east_firearm_dusk','east_firearm_night','east_grocerie_dawn','east_grocerie_day','east_grocerie_dusk','east_grocerie_night','east_guild_dawn','east_guild_day','east_guild_dusk','east_guild_night','east_hotel_dawn','east_hotel_day','east_hotel_dusk','east_hotel_night','east_midtown_dawn','east_midtown_day','east_midtown_dusk','east_midtown_night','east_oldtown_dawn','east_oldtown_day','east_oldtown_dusk','east_oldtown_night','east_restaurant_dawn','east_restaurant_day','east_restaurant_dusk','east_restaurant_night','east_southgate_dawn','east_southgate_day','east_southgate_dusk','east_southgate_night','east_square_dawn','east_square_day','east_square_dusk','east_square_night','east_university_dawn','east_university_day','east_university_dusk','east_university_night','east_uptown_dawn','east_uptown_day','east_uptown_dusk','east_uptown_night'],
  fallen: ['fallen_altar_dawn','fallen_altar_day','fallen_altar_dusk','fallen_altar_night','fallen_altaractive_dawn','fallen_altaractive_day','fallen_altaractive_dusk','fallen_altaractive_night','fallen_basin_dawn','fallen_basin_day','fallen_basin_dusk','fallen_basin_night','fallen_causeway_dawn','fallen_causeway_day','fallen_causeway_dusk','fallen_causeway_night','fallen_entry_dawn','fallen_entry_day','fallen_entry_dusk','fallen_entry_night','fallen_fork_dawn','fallen_fork_day','fallen_fork_dusk','fallen_fork_night'],
  forest: ['forest_cave_day','forest_cave_dusk','forest_cave_night','forest_cliff_day','forest_cliff_dusk','forest_cliff_night','forest_entry_day','forest_entry_dusk','forest_entry_night','forest_glade_day','forest_glade_dusk','forest_glade_night','forest_highland_day','forest_highland_dusk','forest_highland_night','forest_nest_day','forest_nest_dusk','forest_nest_night','forest_shoal_day','forest_shoal_dusk','forest_shoal_night','forest_trail_day','forest_trail_dusk','forest_trail_night','forest_valley_day','forest_valley_dusk','forest_valley_night'],
  holysee: ['holyseedungeonlow','holyseedungeonwhole','lunariaoffice'],
  lake: ['lake_boathouse_dawn','lake_boathouse_day','lake_boathouse_dusk','lake_boathouse_night','lake_causeway_dawn','lake_causeway_day','lake_causeway_dusk','lake_causeway_night','lake_cave_dawn','lake_cave_day','lake_cave_dusk','lake_cave_night','lake_deadfall_dawn','lake_deadfall_day','lake_deadfall_dusk','lake_deadfall_night','lake_eastshore_dawn','lake_eastshore_day','lake_eastshore_dusk','lake_eastshore_night','lake_fallbase_dawn','lake_fallbase_day','lake_fallbase_dusk','lake_fallbase_night','lake_grove_dawn','lake_grove_day','lake_grove_dusk','lake_grove_glow_dawn','lake_grove_glow_day','lake_grove_glow_dusk','lake_grove_glow_night','lake_grove_night','lake_inlet_dawn','lake_inlet_day','lake_inlet_dusk','lake_inlet_night','lake_northshore_dawn','lake_northshore_day','lake_northshore_dusk','lake_northshore_night','lake_shingle_dawn','lake_shingle_day','lake_shingle_dusk','lake_shingle_night'],
  northport: ['northport_cemetery_bf','northport_cemetery_dawn','northport_cemetery_day','northport_cemetery_dusk','northport_cemetery_night','northport_church_bf','northport_church_dawn','northport_church_day','northport_church_dusk','northport_church_night','northport_cityhall_bf','northport_cityhall_dawn','northport_cityhall_day','northport_cityhall_dusk','northport_cityhall_night','northport_east_bf','northport_east_dawn','northport_east_day','northport_east_dusk','northport_east_night','northport_grocery_bf','northport_grocery_dawn','northport_grocery_day','northport_grocery_dusk','northport_grocery_night','northport_guild_bf','northport_guild_dawn','northport_guild_day','northport_guild_dusk','northport_guild_night','northport_gunstore_bf','northport_gunstore_dawn','northport_gunstore_day','northport_gunstore_dusk','northport_gunstore_night','northport_hotel_bf','northport_hotel_dawn','northport_hotel_day','northport_hotel_dusk','northport_hotel_night','northport_hotel_room_dawn','northport_hotel_room_dusk','northport_hotel_room_night','northport_north_bf','northport_north_dawn','northport_north_day','northport_north_dusk','northport_north_night','northport_port_bf','northport_port_dawn','northport_port_day','northport_port_dusk','northport_port_night','northport_square_bf','northport_square_dawn','northport_square_day','northport_square_dusk','northport_square_night','northport_tavern_bf','northport_tavern_dawn','northport_tavern_day','northport_tavern_dusk','northport_tavern_night','northport_west_bf','northport_west_dawn','northport_west_day','northport_west_dusk','northport_west_night'],
  plains: ['plains_beacon_dawn','plains_beacon_day','plains_beacon_dusk','plains_beacon_night','plains_cairn_dawn','plains_cairn_day','plains_cairn_dusk','plains_cairn_night','plains_deadwood_dawn','plains_deadwood_day','plains_deadwood_dusk','plains_deadwood_night','plains_entry_dawn','plains_entry_day','plains_entry_dusk','plains_entry_night','plains_gorge_dawn','plains_gorge_day','plains_gorge_dusk','plains_gorge_night','plains_scree_dawn','plains_scree_day','plains_scree_dusk','plains_scree_night','plains_sea_dawn','plains_sea_day','plains_sea_dusk','plains_sea_night','plains_stone_dawn','plains_stone_day','plains_stone_dusk','plains_stone_night','plains_well_dawn','plains_well_day','plains_well_dusk','plains_well_night','plains_windrock_dawn','plains_windrock_day','plains_windrock_dusk','plains_windrock_night'],
  ravnsdal: ['ravn_bistro','ravn_cafe','ravn_dessert','ravn_dining_dawn','ravn_dining_day','ravn_dining_dusk','ravn_dining_night','ravn_firearm','ravn_grocerie','ravn_guild','ravn_hotel','ravn_library','ravn_lookout_dawn','ravn_lookout_day','ravn_lookout_dusk','ravn_lookout_night','ravn_midtown_dawn','ravn_midtown_day','ravn_midtown_dusk','ravn_midtown_night','ravn_oldtown_dawn','ravn_oldtown_day','ravn_oldtown_dusk','ravn_oldtown_night','ravn_restaurant','ravn_square_dawn','ravn_square_day','ravn_square_dusk','ravn_square_night','ravn_station_dawn','ravn_station_day','ravn_station_dusk','ravn_station_night','ravn_uptown_dawn','ravn_uptown_day','ravn_uptown_dusk','ravn_uptown_night','varn_bistro','varn_cafe','varn_church_dawn','varn_church_day','varn_church_dusk','varn_church_night','varn_dessert','varn_dining_dawn','varn_dining_day','varn_dining_dusk','varn_dining_night','varn_firearm','varn_grocerie','varn_guild','varn_hotel','varn_hotel_dawn','varn_hotel_day','varn_hotel_dusk','varn_hotel_night','varn_library','varn_lookout_dawn','varn_lookout_day','varn_lookout_dusk','varn_lookout_night','varn_midtown_dawn','varn_midtown_day','varn_midtown_dusk','varn_midtown_night','varn_oldtown_dawn','varn_oldtown_day','varn_oldtown_dusk','varn_oldtown_night','varn_restaurant','varn_square_dawn','varn_square_day','varn_square_dusk','varn_square_night','varn_station_dawn','varn_station_day','varn_station_dusk','varn_station_night','varn_uptown_dawn','varn_uptown_day','varn_uptown_dusk','varn_uptown_night'],
  ruins: ['04ae70ed-bb61-4ce7-95a7-2233fd46bce3','1ecacfb0-6e0b-44d2-bc6d-07bb502e02de','28fff50a-2904-4d7f-8176-437dda559f43','366f940f-4fbc-481f-afe8-a58ed24a695c','4e371955-0fdd-4c94-88eb-ec2f8a4d3b1a','4e672af0-1c8e-4ffa-9e05-225823f50205','55e2af51-5ff6-45e6-abcc-9ac22b163193','69063c90-80b0-45b2-a2a1-f1aa8619347e','7607eb61-fd2a-4908-9303-c083e92ee15f','7bba4a5e-6772-438a-807f-5a052c7b81ea','826e1a00-7e30-4938-8959-9f50c71215ae','8d288356-e686-4c5a-8ebf-7a6e6679c736','8f8b1fcb-f329-42d9-ad01-c5feb2c2d785','a27c81d7-5f81-4de8-b0ee-825949729fa6','ab40ead1-35b4-4b50-aefa-a04b5d318929','b303787f-6bed-45b3-87cc-f8ea77d7041d','ef9380a6-9f3c-475e-adc1-c7f9f28896b3','f4b7ac34-bf8c-4711-b6e1-a708b4f00607','ruins_flooded','ruins_guardians','ruins_muralgallery','ruins_observatory_dawn','ruins_observatory_day','ruins_observatory_dusk','ruins_observatory_night','ruins_pillarhall_dawn','ruins_pillarhall_day','ruins_pillarhall_dusk','ruins_pillarhall_night','ruins_ritual','ruins_rotunda_dawn','ruins_rotunda_day','ruins_rotunda_dusk','ruins_rotunda_night','ruins_sarcophagus_dawn','ruins_sarcophagus_day','ruins_sarcophagus_dusk','ruins_sarcophagus_night','ruins_shinier_antechamber_dawn','ruins_shinier_antechamber_day','ruins_shinier_antechamber_dusk','ruins_shinier_antechamber_night','ruins_shinier_brazier','ruins_shinier_bridge','ruins_shinier_bridgeopen','ruins_shinier_catacomb','ruins_shinier_collapsed_dawn','ruins_shinier_collapsed_day','ruins_shinier_collapsed_dusk','ruins_shinier_collapsed_night','ruins_shinier_colossus','ruins_shinier_corridora_dawn','ruins_shinier_corridora_day','ruins_shinier_corridora_dusk','ruins_shinier_corridora_night','ruins_shinier_corridorb_dawn','ruins_shinier_corridorb_day','ruins_shinier_corridorb_dusk','ruins_shinier_corridorb_night','ruins_shinier_crossway_dawn','ruins_shinier_crossway_day','ruins_shinier_crossway_dusk','ruins_shinier_crossway_night','ruins_shinier_darkbridge','ruins_shinier_deepaltar','ruins_shinier_deepaltaractive','ruins_shinier_deepspring','ruins_shinier_entrance','ruins_shinier_entrance_dawn','ruins_shinier_entrance_day','ruins_shinier_entrance_dusk','ruins_shinier_entrance_night','ruins_shinier_hollow','ruins_shinier_machine','ruins_shinier_mosschamber','ruins_shinier_mural','ruins_shinier_prison','ruins_shinier_rift','ruins_shinier_stairdeep','ruins_shinier_stairup','ruins_shinier_well','ruins_spring_dawn','ruins_spring_day','ruins_spring_dusk','ruins_spring_night','ruins_stairdown_dawn','ruins_stairdown_day','ruins_stairdown_dusk','ruins_stairdown_night','ruins_throne_dawn','ruins_throne_day','ruins_throne_dusk','ruins_throne_night','ruins_vault_dawn','ruins_vault_day','ruins_vault_dusk','ruins_vault_night'],
  shinier: ['shinier_altar_dawn','shinier_altar_day','shinier_altar_dusk','shinier_altar_night','shinier_chiefhouse_dawn','shinier_chiefhouse_day','shinier_chiefhouse_dusk','shinier_chiefhouse_night','shinier_east_dawn','shinier_east_day','shinier_east_dusk','shinier_east_night','shinier_grocery_dawn','shinier_grocery_day','shinier_grocery_dusk','shinier_grocery_night','shinier_huntercabin_dawn','shinier_huntercabin_day','shinier_huntercabin_dusk','shinier_huntercabin_night','shinier_lakeside_dawn','shinier_lakeside_day','shinier_lakeside_dusk','shinier_lakeside_night','shinier_north_dawn','shinier_north_day','shinier_north_dusk','shinier_north_night','shinier_plaza_dawn','shinier_plaza_day','shinier_plaza_dusk','shinier_plaza_night','shinier_restaurant_dawn','shinier_restaurant_day','shinier_restaurant_dusk','shinier_restaurant_night','shinier_soranahouse_dawn','shinier_soranahouse_day','shinier_soranahouse_dusk','shinier_soranahouse_night','shinier_west_dawn','shinier_west_day','shinier_west_dusk','shinier_west_night','shinier_wilds_dawn','shinier_wilds_day','shinier_wilds_dusk','shinier_wilds_night','shinier_workshop_dawn','shinier_workshop_day','shinier_workshop_dusk'],
  sofia: ['sofia_bar_day','sofia_bar_dusk','sofia_bar_night','sofia_bistro','sofia_church','sofia_cityhall','sofia_dock','sofia_downtown','sofia_firearm','sofia_grocerie','sofia_guild','sofia_hotel','sofia_inn_dawn','sofia_inn_day','sofia_inn_dusk','sofia_inn_night','sofia_midtown','sofia_restaurant','sofia_slum','sofia_square','sofia_uptown','sofiaout_avenue','sofiaout_backhall','sofiaout_carriage','sofiaout_cellar','sofiaout_forecourt','sofiaout_hall','sofiaout_lodge','sofiaout_road','sofiaout_salon','sofiaout_terrace'],
  tomb: ['tomb_adit','tomb_aislew','tomb_ambulatory','tomb_apse_dawn','tomb_apse_day','tomb_apse_dusk','tomb_apse_night','tomb_ashpit','tomb_bonepit','tomb_brokenhall','tomb_censerroom','tomb_chantry','tomb_chapel','tomb_charnel','tomb_chimney','tomb_cistern','tomb_cloister','tomb_colonnade','tomb_confessio','tomb_corr2','tomb_crossing','tomb_crossvault','tomb_crypt','tomb_crypta','tomb_cryptwalk','tomb_deepwalk','tomb_falsestair','tomb_gallery3','tomb_gate_dawn','tomb_gate_day','tomb_gate_dusk','tomb_gate_night','tomb_gate_sealed_dawn','tomb_gate_sealed_day','tomb_gate_sealed_dusk','tomb_gate_sealed_night','tomb_graveldrop','tomb_hall2','tomb_kiln','tomb_landing2','tomb_landing3','tomb_lapidarium','tomb_lowaltar','tomb_lowaltar_off','tomb_mason','tomb_masonhall','tomb_mudpit','tomb_nave','tomb_nichehall','tomb_nitrepit','tomb_ossuary','tomb_ossuary2','tomb_ossuarya','tomb_reliquary','tomb_rotunda','tomb_rubble','tomb_sacristy','tomb_saltroom','tomb_sarce','tomb_scriptorium','tomb_shaft','tomb_stair1','tomb_stair2','tomb_sump','tomb_sunkhall','tomb_tombniche','tomb_toolniche','tomb_urnvault','tomb_vaultw','tomb_vestibule','tomb_waterstair','tomb_wellyard'],
  verafond: ['vela_harbor_day','vela_midtown_day','vela_portmarket_day','vela_square_day'],
};
/* 展開成 名字→資料夾（省掉重複的資料夾字串，整份小一半）。 */
export const BG_INDEX = (()=>{ const m = Object.create(null);
  for(const dir in G) for(const n of G[dir]) m[n] = dir;
  return m; })();
/* `name` 可以帶副檔名、帶時段尾巴 —— 進來先去副檔名再轉小寫。
   查不到回 `''`（＝根目錄），呼叫端直接接在 BG_DIR 後面。 */
export function bgFolder(name){
  const k = String(name||'').replace(/\.(webp|png|jpe?g)$/i, '').toLowerCase();
  const d = BG_INDEX[k];
  return d ? d + '/' : '';
}
